apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spincli-4549
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spincli-4549
  template:
    metadata:
      labels:
        app: spincli-4549
    spec:
      containers:
        - image: 'docker.io/opsmx11/restapp:restapp_spincli-1.1'
          imagePullPolicy: Always
          name: restapp
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9090
              name: prometheus
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: spincli-service
  namespace: default
spec:
  ports:
    - name: canary
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: reports
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: spincli-4549
  type: NodePort
      
